export const autoriFamosi: string[] = [
    'J.K. Rowling',
    'George R.R. Martin',
    'Agatha Christie',
    'Mark Twain',
    'Ernest Hemingway',
    'Jane Austen',
    'F. Scott Fitzgerald',
    'Friedrich Nietzsche',
    'Leo Tolstoy',
    'Gabriel García Márquez',
    'Harper Lee',
    'Stephen King',
    'Toni Morrison',
    'Charles Dickens',
    'Virginia Woolf',
    'Herman Melville',
    'George Orwell',
    'Margaret Atwood',
    'Isaac Asimov',
    'Ray Bradbury',
    'Kurt Vonnegut',
    'C.S. Lewis',
    'John Steinbeck',
    'Dostoevskij',
    'Emily Dickinson',
    'Oscar Wilde',
    'Robert Louis Stevenson',
    'Jules Verne',
    'Dante Alighieri',
    'Mark Haddon',
    'Dan Brown',
    'Neil Gaiman',
    'Philip K. Dick',
    'Stephen Hawking',
    'Paulo Coelho',
    'Zadie Smith',
    'Maya Angelou',
    'Chinua Achebe',
    'Khaled Hosseini',
    'Malcolm Gladwell',
    'John Green'
];
